/**
 * Mock Appointments Data
 * 30+ appointment records with various statuses
 */

export const MOCK_APPOINTMENTS = [
  {
    _id: 'apt1',
    patient: 'p1',
    patientName: 'John Doe',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-20',
    startAt: '2024-03-20T09:00:00Z',
    endAt: '2024-03-20T09:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'First consultation for back pain',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-15',
  },
  {
    _id: 'apt2',
    patient: 'p2',
    patientName: 'Jane Smith',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-20',
    startAt: '2024-03-20T10:00:00Z',
    endAt: '2024-03-20T10:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Follow-up for diabetes management',
    vitals: {
      bloodPressure: '120/80',
      temperature: '98.6',
      weight: '65',
      height: '165',
      pulse: '72',
    },
    clinicalNotes: {
      diagnosis: 'Type 2 Diabetes - Well controlled',
      symptoms: 'No new symptoms reported',
      examination: 'Blood sugar levels stable',
      treatment: 'Continue current medication',
    },
    prescriptions: ['rx1', 'rx2'],
    createdAt: '2024-03-10',
  },
  {
    _id: 'apt3',
    patient: 'p3',
    patientName: 'Michael Johnson',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-20',
    startAt: '2024-03-20T11:00:00Z',
    endAt: '2024-03-20T11:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Hypertension follow-up',
    vitals: {
      bloodPressure: '140/90',
      temperature: '98.4',
      weight: '82',
      height: '178',
      pulse: '78',
    },
    clinicalNotes: {
      diagnosis: 'Hypertension',
      symptoms: 'Occasional headaches',
      examination: 'BP slightly elevated',
      treatment: 'Adjust medication dosage',
    },
    prescriptions: ['rx3'],
    createdAt: '2024-03-08',
  },
  {
    _id: 'apt4',
    patient: 'p4',
    patientName: 'Emily Davis',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-21',
    startAt: '2024-03-21T09:00:00Z',
    endAt: '2024-03-21T09:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'General checkup',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-18',
  },
  {
    _id: 'apt5',
    patient: 'p5',
    patientName: 'Robert Wilson',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-21',
    startAt: '2024-03-21T10:00:00Z',
    endAt: '2024-03-21T10:30:00Z',
    type: 'follow_up',
    status: 'confirmed',
    notes: 'Arthritis management',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-12',
  },
  {
    _id: 'apt6',
    patient: 'p6',
    patientName: 'Sarah Brown',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-19',
    startAt: '2024-03-19T14:00:00Z',
    endAt: '2024-03-19T14:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Asthma follow-up',
    vitals: {
      bloodPressure: '118/76',
      temperature: '98.2',
      weight: '58',
      height: '162',
      pulse: '68',
    },
    clinicalNotes: {
      diagnosis: 'Asthma - Controlled',
      symptoms: 'No recent attacks',
      examination: 'Lung sounds clear',
      treatment: 'Continue inhaler as needed',
    },
    prescriptions: ['rx4'],
    createdAt: '2024-03-14',
  },
  {
    _id: 'apt7',
    patient: 'p7',
    patientName: 'David Martinez',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-22',
    startAt: '2024-03-22T09:00:00Z',
    endAt: '2024-03-22T09:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'Chest pain evaluation',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-19',
  },
  {
    _id: 'apt8',
    patient: 'p8',
    patientName: 'Lisa Anderson',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-18',
    startAt: '2024-03-18T15:00:00Z',
    endAt: '2024-03-18T15:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Thyroid disorder management',
    vitals: {
      bloodPressure: '115/75',
      temperature: '98.6',
      weight: '62',
      height: '160',
      pulse: '70',
    },
    clinicalNotes: {
      diagnosis: 'Hypothyroidism',
      symptoms: 'Energy levels improved',
      examination: 'TSH levels normal',
      treatment: 'Continue current dosage',
    },
    prescriptions: ['rx5'],
    createdAt: '2024-03-09',
  },
  {
    _id: 'apt9',
    patient: 'p9',
    patientName: 'James Taylor',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-22',
    startAt: '2024-03-22T11:00:00Z',
    endAt: '2024-03-22T11:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'Sports injury consultation',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-20',
  },
  {
    _id: 'apt10',
    patient: 'p10',
    patientName: 'Patricia Thomas',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-17',
    startAt: '2024-03-17T10:00:00Z',
    endAt: '2024-03-17T10:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Migraine management',
    vitals: {
      bloodPressure: '122/78',
      temperature: '98.4',
      weight: '60',
      height: '158',
      pulse: '74',
    },
    clinicalNotes: {
      diagnosis: 'Chronic Migraine',
      symptoms: 'Reduced frequency of attacks',
      examination: 'Neurological exam normal',
      treatment: 'Continue preventive medication',
    },
    prescriptions: ['rx6'],
    createdAt: '2024-03-07',
  },
  {
    _id: 'apt11',
    patient: 'p11',
    patientName: 'Christopher Lee',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-23',
    startAt: '2024-03-23T09:00:00Z',
    endAt: '2024-03-23T09:30:00Z',
    type: 'follow_up',
    status: 'scheduled',
    notes: 'Anxiety disorder follow-up',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-16',
  },
  {
    _id: 'apt12',
    patient: 'p12',
    patientName: 'Jennifer White',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-16',
    startAt: '2024-03-16T14:00:00Z',
    endAt: '2024-03-16T14:30:00Z',
    type: 'first_visit',
    status: 'completed',
    notes: 'Skin rash evaluation',
    vitals: {
      bloodPressure: '120/80',
      temperature: '98.6',
      weight: '64',
      height: '168',
      pulse: '72',
    },
    clinicalNotes: {
      diagnosis: 'Allergic Dermatitis',
      symptoms: 'Itchy rash on arms',
      examination: 'Mild inflammation observed',
      treatment: 'Topical steroid cream prescribed',
    },
    prescriptions: ['rx7'],
    createdAt: '2024-03-14',
  },
  {
    _id: 'apt13',
    patient: 'p13',
    patientName: 'Daniel Harris',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-23',
    startAt: '2024-03-23T10:30:00Z',
    endAt: '2024-03-23T11:00:00Z',
    type: 'follow_up',
    status: 'scheduled',
    notes: 'GERD management',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-18',
  },
  {
    _id: 'apt14',
    patient: 'p14',
    patientName: 'Nancy Clark',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-15',
    startAt: '2024-03-15T09:00:00Z',
    endAt: '2024-03-15T09:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Osteoporosis follow-up',
    vitals: {
      bloodPressure: '125/82',
      temperature: '98.4',
      weight: '58',
      height: '155',
      pulse: '70',
    },
    clinicalNotes: {
      diagnosis: 'Osteoporosis',
      symptoms: 'No new fractures',
      examination: 'Bone density stable',
      treatment: 'Continue calcium and vitamin D',
    },
    prescriptions: ['rx8'],
    createdAt: '2024-03-02',
  },
  {
    _id: 'apt15',
    patient: 'p15',
    patientName: 'Matthew Lewis',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-24',
    startAt: '2024-03-24T09:00:00Z',
    endAt: '2024-03-24T09:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'Sleep disorder consultation',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-20',
  },
  // More appointments for variety
  {
    _id: 'apt16',
    patient: 'p16',
    patientName: 'Karen Walker',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-14',
    startAt: '2024-03-14T11:00:00Z',
    endAt: '2024-03-14T11:30:00Z',
    type: 'follow_up',
    status: 'cancelled',
    notes: 'Patient cancelled - rescheduled',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-10',
  },
  {
    _id: 'apt17',
    patient: 'p17',
    patientName: 'Kevin Hall',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-24',
    startAt: '2024-03-24T14:00:00Z',
    endAt: '2024-03-24T14:30:00Z',
    type: 'follow_up',
    status: 'scheduled',
    notes: 'Depression follow-up',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-19',
  },
  {
    _id: 'apt18',
    patient: 'p18',
    patientName: 'Betty Allen',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-13',
    startAt: '2024-03-13T15:00:00Z',
    endAt: '2024-03-13T15:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Cholesterol management',
    vitals: {
      bloodPressure: '130/85',
      temperature: '98.6',
      weight: '70',
      height: '165',
      pulse: '76',
    },
    clinicalNotes: {
      diagnosis: 'Hyperlipidemia',
      symptoms: 'No symptoms',
      examination: 'Lipid panel improved',
      treatment: 'Continue statin therapy',
    },
    prescriptions: ['rx9'],
    createdAt: '2024-02-26',
  },
  {
    _id: 'apt19',
    patient: 'p19',
    patientName: 'Brian Young',
    doctor: 'd2',
    doctorName: 'Dr. John Williams',
    clinic: 'clinic1',
    date: '2024-03-25',
    startAt: '2024-03-25T09:00:00Z',
    endAt: '2024-03-25T09:30:00Z',
    type: 'first_visit',
    status: 'scheduled',
    notes: 'Knee pain evaluation',
    vitals: null,
    clinicalNotes: null,
    createdAt: '2024-03-21',
  },
  {
    _id: 'apt20',
    patient: 'p20',
    patientName: 'Dorothy King',
    doctor: 'd1',
    doctorName: 'Dr. Sarah Smith',
    clinic: 'clinic1',
    date: '2024-03-12',
    startAt: '2024-03-12T10:00:00Z',
    endAt: '2024-03-12T10:30:00Z',
    type: 'follow_up',
    status: 'completed',
    notes: 'Chronic kidney disease monitoring',
    vitals: {
      bloodPressure: '135/88',
      temperature: '98.4',
      weight: '66',
      height: '160',
      pulse: '74',
    },
    clinicalNotes: {
      diagnosis: 'CKD Stage 3',
      symptoms: 'Fatigue improved',
      examination: 'Creatinine levels stable',
      treatment: 'Continue current regimen',
    },
    prescriptions: ['rx10'],
    createdAt: '2024-02-24',
  },
];

/**
 * Get appointment by ID
 */
export const getAppointmentById = (id) => {
  return MOCK_APPOINTMENTS.find(a => a._id === id);
};

/**
 * Get appointments by patient ID
 */
export const getAppointmentsByPatient = (patientId) => {
  return MOCK_APPOINTMENTS.filter(a => a.patient === patientId);
};

/**
 * Get today's appointments
 */
export const getTodaysAppointments = () => {
  const today = new Date().toISOString().split('T')[0];
  return MOCK_APPOINTMENTS.filter(a => a.date === today);
};

/**
 * Filter appointments
 */
export const filterAppointments = (filters) => {
  let filtered = [...MOCK_APPOINTMENTS];

  if (filters.status && filters.status !== 'all') {
    filtered = filtered.filter(a => a.status === filters.status);
  }

  if (filters.doctor && filters.doctor !== 'all') {
    filtered = filtered.filter(a => a.doctor === filters.doctor);
  }

  if (filters.startDate && filters.endDate) {
    filtered = filtered.filter(a => 
      a.date >= filters.startDate && a.date <= filters.endDate
    );
  }

  return filtered;
};
